/**
 * GET /api/secrets — Returns all secrets from CREDENTIALS_JSON, grouped by service.
 *
 * Secrets are generated by OpenTofu and stored as a Cloudflare Pages secret
 * during spin-up. This endpoint reads and groups them for display in the
 * Control Panel Secrets page.
 */

// Map secret key prefixes to human-readable group names
const GROUP_MAP = {
  'admin_':        { name: 'Admin / Config',     order: 0 },
  'infisical_':    { name: 'Infisical',          order: 1 },
  'portainer_':    { name: 'Portainer',          order: 2 },
  'grafana_':      { name: 'Grafana',            order: 3 },
  'kuma_':         { name: 'Uptime Kuma',        order: 4 },
  'postgres_':     { name: 'PostgreSQL',         order: 5 },
  'pgadmin_':      { name: 'pgAdmin',            order: 6 },
  'gitea_':        { name: 'Gitea',              order: 7 },
  'woodpecker_':   { name: 'Woodpecker CI',      order: 8 },
  'kestra_':       { name: 'Kestra',             order: 9 },
  'n8n_':          { name: 'n8n',                order: 10 },
  'dagster_':      { name: 'Dagster',            order: 11 },
  'prefect_':      { name: 'Prefect',            order: 12 },
  'windmill_':     { name: 'Windmill',           order: 13 },
  'meltano_':      { name: 'Meltano',            order: 14 },
  'metabase_':     { name: 'Metabase',           order: 15 },
  'clickhouse_':   { name: 'ClickHouse',         order: 16 },
  'openmetadata_': { name: 'OpenMetadata',       order: 17 },
  'minio_':        { name: 'MinIO',              order: 18 },
  'rustfs_':       { name: 'RustFS',             order: 19 },
  'seaweedfs_':    { name: 'SeaweedFS',          order: 20 },
  'garage_':       { name: 'Garage',             order: 21 },
  'lakefs_':       { name: 'LakeFS',             order: 22 },
  'filestash_':    { name: 'Filestash',          order: 23 },
  'redpanda_':     { name: 'Redpanda',           order: 24 },
  'cloudbeaver_':  { name: 'CloudBeaver',        order: 25 },
  'mage_':         { name: 'Mage AI',            order: 26 },
  'hoppscotch_':   { name: 'Hoppscotch',         order: 27 },
  'nocodb_':       { name: 'NocoDB',             order: 28 },
  'dinky_':        { name: 'Dinky',              order: 29 },
  'dify_':         { name: 'Dify',               order: 30 },
  'wikijs_':       { name: 'Wiki.js',            order: 31 },
  'soda_':         { name: 'Soda',               order: 32 },
  'hetzner_s3_':   { name: 'Hetzner S3',         order: 33 },
  'external_s3_':  { name: 'External S3',        order: 34 },
  'r2_data_':      { name: 'Cloudflare R2',      order: 35 },
  'dockerhub_':    { name: 'Docker Hub',         order: 36 },
};

function getGroup(key) {
  for (const [prefix, info] of Object.entries(GROUP_MAP)) {
    if (key.startsWith(prefix)) return info;
  }
  return { name: 'Other', order: 99 };
}

export async function onRequestGet(context) {
  try {
    const credentialsJson = context.env.CREDENTIALS_JSON;
    if (!credentialsJson) {
      return Response.json({
        success: true,
        groups: [],
        message: 'No credentials available. Run Spin Up to generate secrets.',
      });
    }

    const secrets = JSON.parse(credentialsJson);
    const groupedMap = {};

    for (const [key, value] of Object.entries(secrets)) {
      // Skip empty values
      if (!value && value !== 0) continue;

      const groupInfo = getGroup(key);
      if (!groupedMap[groupInfo.name]) {
        groupedMap[groupInfo.name] = { name: groupInfo.name, order: groupInfo.order, secrets: [] };
      }
      groupedMap[groupInfo.name].secrets.push({ key, value: String(value) });
    }

    // Sort groups by order, secrets alphabetically within each group
    const groups = Object.values(groupedMap)
      .sort((a, b) => a.order - b.order)
      .map(g => ({
        name: g.name,
        secrets: g.secrets.sort((a, b) => a.key.localeCompare(b.key)),
      }));

    return Response.json({ success: true, groups });
  } catch (error) {
    return Response.json({ success: false, error: error.message }, { status: 500 });
  }
}
